description: ""
type: object
properties:
  site_settings:
    type: array
    uniqueItems: true
    minItems: 1
    items:
      required:
        - setting
        - description
        - default
        - type
        - value
        - category
        - preview
        - translate_names
      properties:
        setting:
          type: string
          minLength: 1
        description:
          type: string
          minLength: 1
        default:
          type: string
          minLength: 1
        type:
          type: string
          minLength: 1
        value:
          type: string
          minLength: 1
        category:
          type: string
          minLength: 1
        preview:
          type: string
          minLength: 1
        valid_values:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            required:
              - name
              - value
            properties:
              name:
                type: string
                minLength: 1
              value:
                type: string
                minLength: 1
        translate_names:
          type: boolean
        choices:
          type: array
          uniqueItems: null
          minItems: null
          items:
            type: object
  diags:
    type: object
    properties:
      last_message_processed:
        type: object
